# Generated by Django 3.1 on 2020-08-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='about_author',
            field=models.CharField(max_length=100),
        ),
    ]
