# Generated by Django 3.1 on 2020-08-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200817_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='about_designation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='about_author',
            field=models.TextField(),
        ),
    ]
