# Generated by Django 3.0.5 on 2020-08-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_auto_20200806_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='headline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
