# Generated by Django 3.0.5 on 2020-08-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0006_auto_20200806_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='occupation',
            new_name='headline',
        ),
    ]
