# Generated by Django 3.0.5 on 2020-08-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0008_auto_20200806_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='say_something_about_yourself',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
