# Generated by Django 3.0.5 on 2020-08-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0009_auto_20200808_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
