# Generated by Django 3.0.5 on 2020-08-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0010_user_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='say_something_about_yourself',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
