# Generated by Django 3.1 on 2020-08-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hero_background_image',
            field=models.ImageField(blank=True, upload_to='item_image'),
        ),
    ]
