# Generated by Django 3.1 on 2020-08-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20200824_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_image'),
        ),
        migrations.AlterField(
            model_name='company',
            name='hero_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_image'),
        ),
    ]
