# Generated by Django 3.1 on 2020-08-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20200824_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='opentiming',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_color', models.CharField(max_length=100)),
                ('welcome_color', models.CharField(max_length=100)),
                ('header_color', models.CharField(max_length=100)),
                ('header_font', models.CharField(max_length=100)),
                ('sub_header_font', models.CharField(max_length=100)),
                ('sub_header_color', models.CharField(max_length=100)),
                ('button_color', models.CharField(max_length=100)),
                ('p_color', models.CharField(max_length=100)),
                ('p_font', models.CharField(max_length=100)),
                ('hover_color', models.CharField(max_length=100)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
