# Generated by Django 3.1 on 2020-08-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20200825_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'verbose_name_plural': 'Design'},
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company_logo'),
        ),
        migrations.AlterField(
            model_name='design',
            name='bg_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='design',
            name='button_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='design',
            name='header_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='design',
            name='header_font',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='design',
            name='hover_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='design',
            name='p_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='design',
            name='p_font',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='design',
            name='sub_header_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='design',
            name='sub_header_font',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='design',
            name='welcome_color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
