# Generated by Django 3.1 on 2020-08-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20200825_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='des_of_company',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
