# Generated by Django 3.1.2 on 2020-10-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20200916_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='image',
        ),
        migrations.AlterField(
            model_name='items',
            name='stock',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.items')),
            ],
            options={
                'verbose_name_plural': 'ItemImage',
            },
        ),
    ]
